name: Build and Test Dockerized App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install mongosh
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend Docker image
        run: docker build -t todoapp-frontend ./client

      - name: Build backend Docker image
        run: docker build -t todoapp-backend ./server

      - name: Run backend container (test only)
        run: |
          docker run -d --name test-backend \
            -e MONGO_URI=mongodb://localhost:27017/tododb \
            todoapp-backend

      - name: Test backend inside container
        run: |
          sleep 10
          docker exec test-backend curl --fail http://localhost:5001/api/tasks || (echo "❌ Backend not reachable inside container" && exit 1)
