name: Build and Test Dockerized App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports: ['27017:27017']
        options: --health-cmd "mongo --eval 'db.stats()'" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend Docker image
        run: |
          docker build -t todoapp-frontend ./client

      - name: Build backend Docker image
        run: |
          docker build -t todoapp-backend ./server

      - name: Run backend container (test only)
        run: |
          docker run -d --name test-backend --network host -e MONGO_URI=mongodb://localhost:27017/tododb todoapp-backend

      - name: Wait and test backend health (optional ping route)
        run: |
          sleep 10
          curl http://localhost:5001/api/tasks || echo "App not reachable yet"

